name          'saw-multiinstall'
version       '0.1.0'
source        'https://github.com/ScottWales/puppet-multiinstall'
author        'saw'
license       'Apache 2.0'
summary       'Install multiple versions of a program'
description   ''
project_page  'https://github.com/ScottWales/puppet-multiinstall'

dependency 'puppetlabs/stdlib'
